#!/bin/sh

# nohup ./get-tweets&
# also in /etc/rc.local to run after reboot

source /home/ec2-user/.bash_profile

cd /home/ec2-user/functal/titles

while :
do
    python3 -u ./get-tweets.py
    sleep 1
done
