#!/bin/sh

#convert a single jpg to svg, then jpg & transfer to s3
# then delete them

# bulk rename example
#aws s3 ls s3://functal-images | grep  "\-svg" | tee svg.txt
#cat svg.txt | awk '{ x=$4; gsub(/functal-a003-/, "functal-", $4); gsub(/.jpg/, "-svg.jpg", $4);  print  "aws s3 mv s3://functal-images/" x " s3://functal-images/" $4 " --acl='public-read'"}' > ~/Projects/functal/ren.sh


echo $1

echo create svg
node --harmony svg-image.js "$1"

if [ -s "${1/\.jpg/.svg}" ]
then
  echo convert to jpg

  time=`date +%s`
  out=${1/\.jpg/-svg-}$time.jpg

  svg=${1/\.jpg/.svg}

  rsvg-convert --unlimited "$svg" | convert - "$out"

  if curl -s http://169.254.169.254/latest/meta-data/spot/termination-time | grep -q .*T.*Z; then
    echo terminated;
  else
    echo copy to s3
    aws s3 cp "$out" s3://functal-images --acl="public-read"
  fi

else
  echo zero length file
fi

echo delete
rm "$1" "$svg" "$out"
