#!/bin/sh

#convert a single jpg to svg, then jpg & transfer to s3
# then delete them

echo $1

echo create svg
node --harmony svg-image.js "$1"

if [ -s "${1/\.jpg/.svg}" ]
then
  echo convert to jpg
  rsvg-convert --unlimited "${1/\.jpg/.svg}" | convert - "${1/functal/functal-a}"

  echo copy to s3
  aws s3 cp "${1/functal/functal-a}" s3://functal-images --acl="public-read"
else
  echo zero length file
fi

echo delete
rm "$1" "${1/\.jpg/.svg}" "${1/functal/functal-a}"
