#!/bin/sh

echo Loading files...

start=`date +%s`

# creat elist of just original functal file names
aws s3 ls s3://functal-images | grep -ve  "-\(svg\|wgl\|3d\)" | awk '{ print $4 }' > /tmp/files

mkdir -p /data/process

rm /data/process/*

while :
do
  # pick a random file
  file=`sort --sort=random /tmp/files | head -n 1`

  # download it
  aws s3 cp s3://functal-images/$file /data/process/$file

  # process it
  ./create-svg /data/process/$file

  # exit if over 55 minutes
  now=`date +%s`
  runtime=$(((now-start)/60))

  echo runtime $runtime

  # if [ $runtime -ge 55 ]; then
  #   break
  # fi

  if curl -s http://169.254.169.254/latest/meta-data/spot/termination-time | grep -q .*T.*Z; then
    echo terminated
    break
  fi

done

sudo shutdown -h now

