#!/bin/sh

# in /etc/rc.local
# sudo -u ec2-user /home/ec2-user/functal/svg-create

cd /home/ec2-user/functal

date >> /home/ec2-user/debug.txt

git pull -X theirs >> /home/ec2-user/debug.txt

./svg-create-files
