#!/bin/sh

# nohup ./serve&
# also in /etc/rc.local to run after reboot
# who -b shows last reboot date

source /home/ec2-user/.bash_profile

cd /home/ec2-user/functal/admin

while :
do
    node server-admin.js
    sleep 1
done
